replicaCount: 1

image:
  repository: 713881830177.dkr.ecr.us-east-1.amazonaws.com/eks-cluster-helloworld
  tag: test
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi

# Probes
readinessProbe:
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /
  port: 80
  initialDelaySeconds: 15
  periodSeconds: 20
