replicaCount: 1

image:
  repository: 713881830177.dkr.ecr.us-east-1.amazonaws.com/eks-cluster-helloworld
  tag: 80f3393ba21e255cfbb96c642ea281e2850204c8
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 50m
    memory: 64Mi

# Probes
readinessProbe:
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /
  port: 80
  initialDelaySeconds: 15
  periodSeconds: 20
