replicaCount: 1

image:
  repository: 713881830177.dkr.ecr.us-east-1.amazonaws.com/eks-cluster-helloworld
  tag: 0efdb770e4ea39f36b7daece4f7ec6d84dca5ecc
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    cpu: 10m
    memory: 16Mi
  limits:
    cpu: 50m
    memory: 64Mi

# Probes
readinessProbe:
  path: /
  port: 8080
  initialDelaySeconds: 15
  periodSeconds: 10

livenessProbe:
  path: /
  port: 8080
  initialDelaySeconds: 15
  periodSeconds: 20
